USE healthcare_db;
SHOW TABLES;
SELECT * FROM doctors;
SELECT * FROM appointments;
SELECT * FROM appointments WHERE fee BETWEEN 2000 AND 5000;
SELECT * FROM appointments WHERE fee BETWEEN 500 AND 2000;
SELECT * FROM appointments WHERE fee>= 500 AND fee<= 2000;
SELECT * FROM patients;
SELECT date_of_birth FROM patients ORDER BY date_of_birth ASC;
SELECT * FROM appointments;
SELECT * FROM appointments WHERE status IN('schedule', 'completed', 'cancelled');
SELECT Count(date_of_birth) FROM patients;
SELECT * FROM appointments WHERE status IN('schedule', 'completed', 'cancelled');
SELECT * FROM doctors;
SELECT * FROM doctors WHERE specialty IN('Interventional Cardiology', 'sports medicine');
SELECT * FROM appointments;
SELECT fee FROM appointments;
SELECT count(fee) FROM appointments;
SELECT fee FROM appointments WHERE fee NOT BETWEEN 500 AND 2000;
SELECT fee FROM appointments WHERE fee  BETWEEN 500 AND 2000;
SELECT * FROM appointments WHERE fee  BETWEEN 500 AND 2000;
SELECT * FROM patients WHERE city IN('kolkata', 'mumbai', 'chennai') ORDER BY city;
SELECT city FROM patients;
SELECT * FROM appointments;
SELECT appointment_date from appointments;
SELECT * from appointments where appointment_date>= '2024-01-10' AND appointment_date< '2024-05-01';
SELECT * FROM appointments WHERE fee BETWEEN 1000 AND 5000 ORDER BY fee ASC;
SELECT * FROM appointments WHERE status IN( 'scheduled');
SELECT * FROM appointments WHERE status NOT IN( 'cancelled');
SELECT * FROM appointments WHERE fee NOT BETWEEN 2000 AND 5000;
SELECT count(patient_id) FROM patients;
SELECT count(appointment_id) FROM appointments WHERE status= 'completed';
SELECT COUNT(DISTINCT specialty) FROM doctors;
SELECT DISTINCT specialty FROM doctors;

